name: get clash subscribe app

#on: push
on:
  push:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    - cron: "00 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: read repository
      uses: actions/checkout@v4
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt;fi
    - name: run main
      run: |
        git rm myclash.yaml
        python main.py
        echo "# date: `date`" >> myclash.yaml
        cat tmp.yaml >> myclash.yaml
    - name: print pwd and ls -al
      run: |
        pwd
        ls -al
    - name: push generated file to repository
      run: |
        git config --global user.email "workerusers.noreply.github.com"
        git config --global user.name "clash worker"
        git config --global user.email
        git config --global user.name
        git add myclash.yaml
        git commit -m "add myclash.yaml"
        git remote set-url origin https://github.com/ltcrj/myclash.git
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
        U=${{ secrets.GITEE_NAME }}
        P=${{ secrets.GITEE_P }}
    - name: push myclash.yaml to gitee
      # /home/runner/work/myclash/myclash
      run: |
        cd ../..
        mkdir gitee
        cd gitee
        git init
        git remote add origin git@gitee.com:xnysh/myclash.git
        mv ../myclash/myclash/myclash.yaml .
        echo $T
        pwd
        ls -al
        git add myclash.yaml
        git commit -m 'update myclash.yaml'
        git remote set-url origin https://$U:$P@gitee.com/$U/myclash.git
        git push --set-upstream origin master
