name: get clash subscribe app

on: push
#  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
#    - cron: "00 22 * * *"
#  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: read repository
      uses: actions/checkout@v4
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt;fi
    - name: run main
      run: |
        python main.py
    - name: print pwd and ls -al
      run: |
        pwd
        ls -al
    - name: push generated file to repository
      run: |
        git config --global user.name "workflows user"
        git config --global user.email "workflowsuser@users.noreply.github.com"
        git add myclash.yaml
        git commit -m "add myclash.yaml"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
