name: get clash subscribe app

on: push
#  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
#    - cron: "00 22 * * *"
#  workflow_dispatch:


permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Set up Python 3.12
      uses: sayyid5416/pyinstaller@v1
      with:
        python-version: "3.12"
        spec: 'main.py'
        upload_exe_with_name: 'main'
        options: --onefile, --name "main", windowed
